      PROGRAM MAIN
      INTEGER I, INTPI, INTE
      REAL X, REALPI, REALE
      I = 1
      X = 1
      PRINT *, 'THE VALUE OF 1 AS A REAL IS', X
      PRINT *, 'THE VALUE OF 1 AS AN INTEGER IS', I
      REALPI = 3.1416
      INTPI = REALPI
      PRINT *, 'THE VALUE OF PI AS A REAL IS', REALPI
      PRINT *, 'THE VALUE OF PI AS AN INTEGER IS', INTPI
      REALE = 2.71828
      INTE = REALE
      PRINT *, 'THE VALUE OF E AS A REAL IS', REALE
      PRINT *, 'THE VALUE OF E AS AN INTEGER IS', INTE
      STOP
      END
